[project]
name = "my-pet-chatbot"
version = "0.0.1"
description = "My pet chatbot helper tools"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastembed>=0.7.4",
    "mcp>=1.26.0",
    "pydantic-ai>=1.56.0",
    "pydantic-evals>=1.56.0",
    "pypdf>=6.6.2",
    "qdrant-client>=1.16.2",
]

[project.scripts]
mpet = "tools.cli:app"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["tools"]
